CONTRAST_WEB/CONTRAST_WEB/Controllers/GenerateFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using CONTRAST_WEB.Models;
using System.Text;
using System.IO;
using System.Globalization;
using System.Security.Claims;
using PagedList;

namespace CONTRAST_WEB.Controllers
{
    public class GenerateFileController : Controller
    {
        // GET: GenerateFile
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string currentFilter2, string searchString, string searchString2, int? page, DateTime? startdate, DateTime? enddate)

        {
            var identity = (ClaimsIdentity)User.Identity;
            string[] claims = identity.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
            ViewBag.Privillege = claims;
            tb_m_employee model = await GetData.EmployeeInfo(identity.Name);

            List<GenerateFileHelper> Generate = new List<GenerateFileHelper>();
            List<vw_actualcost_generate_file> data = new List<vw_actualcost_generate_file>();
            data = await GetData.GenerateFileData();

            foreach (var item in data)
            {
                GenerateFileHelper temp = new GenerateFileHelper();
                temp.Entity = item;
                temp.Name = model.name;
                temp.No_Reg = Convert.ToInt32(model.code);
                Generate.Add(temp);
            }


            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
                searchString2 = currentFilter2;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentFilter2 = searchString2;

            if (startdate != null)
                ViewBag.startdate = startdate;
            else
                ViewBag.startdate = null;

            if (enddate != null)
                ViewBag.enddate = enddate;
            else
                ViewBag.enddate = null;

            //filter
            if (!String.IsNullOrEmpty(searchString))
            {
                List<GenerateFileHelper> temp = new List<GenerateFileHelper>();
                for (int k = 0; k < Generate.Count; k++)
                {
                    if (Generate[k].Entity.EMPLOYEE_NAME.ToLower().Contains(searchString.ToLower()) ||
                        Generate[k].Entity.BTR_NO.ToLower().Contains(searchString.ToLower()))
                    {
                        temp.Add(Generate[k]);
                    }
                }
                if (temp.Count() > 0) Generate = temp;
                else Generate = temp;
            }

            //filter
            if (!String.IsNullOrEmpty(searchString2))
            {
                List<GenerateFileHelper> temp = new List<GenerateFileHelper>();
                for (int k = 0; k < Generate.Count; k++)
                {
                    if (Generate[k].Entity.DESTINATION.ToLower().Contains(searchString2.ToLower()) ||
                        Generate[k].Entity.COST_CENTER.ToLower().Contains(searchString2.ToLower()) ||
                        Generate[k].Entity.WBS_ELEMENT.ToLower().Contains(searchString2.ToLower()) ||
                        Generate[k].Entity.TRAVEL_TYPE.ToLower().Contains(searchString2.ToLower()) ||
                        Generate[k].Entity.BUDGET.ToLower().Contains(searchString2.ToLower()) ||
                        Generate[k].Entity.VENDOR_NAME.ToLower().Contains(searchString2.ToLower()))
                    {
                        temp.Add(Generate[k]);
                    }
                }
                if (temp.Count() > 0) Generate = temp;
                else Generate = temp;
            }


            //date filter
            if (startdate != null && enddate != null)
            {
                List<GenerateFileHelper> temp = new List<GenerateFileHelper>();
                for (int k = 0; k < Generate.Count; k++)
                {
                    //by group code
                    if (
                        DateTime.ParseExact(Generate[k].Entity.PV_DATE, "dd.MM.yyyy", CultureInfo.CurrentCulture) >= startdate
                        && DateTime.ParseExact(Generate[k].Entity.PV_DATE, "dd.MM.yyyy", CultureInfo.CurrentCulture) <= enddate
                       )
                        temp.Add(Generate[k]);
                }
                if (temp.Count() > 0) Generate = temp;
            }

            int pageSize = 15;
            int pageNumber = (page ?? 1);

            List<int> id_data = new List<int>();
            for (int k = 0; k < Generate.Count; k++)
                id_data.Add(Generate[k].Entity.id_data);
            ViewBag.id_data = id_data;
            return View("Index", Generate.OrderBy(b => b.Entity.PV_DATE).ToList().ToPagedList(pageNumber, pageSize));     

        }
        
        [HttpPost]
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Generate(List<int>id_data)
        {
            var identity = (ClaimsIdentity)User.Identity;
            string[] claims = identity.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
            ViewBag.Privillege = claims;
            tb_m_employee employee = await GetData.EmployeeInfo(identity.Name);

            List<GenerateFileHelper> model= new List<GenerateFileHelper>();
            for (int k = 0; k < id_data.Count(); k++)
            {
                
                model.Add(new GenerateFileHelper());
                model[k].Entity = await GetData.GenerateFile(id_data[k]);
                model[k].No_Reg = Convert.ToInt32(employee.code);
                model[k].Name = employee.name.Trim();

            }
            //todo: add some data from your database into that string:
            MemoryStream memoryStream = new MemoryStream();
            TextWriter tw = new StreamWriter(memoryStream);
            string MANDT, PV_NO, PV_YEAR, ITEM_NO, PV_DATE, PV_TYPE, TRANS_TYPE, VENDOR, VENDOR_GRP, INVOICE_NO, TAX_NO, PAYMENT_TERM, PAYMENT_METHOD, PLAN_PAYMENT_DT, POSTING_DT, TOTAL_AMOUNT, DPP_AMOUNT, CURRENCY, TAX_CODE, HEADER_TEXT, BANK_TYPE, gl_account, AMOUNT, COST_CENTER, WBS_ELEMENT, ITEM_TEXT, STATUS, SAP_DOC_NO, SAP_DOC_YEAR;
            tw.Write("MANDT\t" +
                "PV_NO\t" +
                "PV_YEAR\t" +
                "ITEM_NO\t" +
                "PV_DATE\t" +
                "PV_TYPE\t" +
                "TRANS_TYPE\t" +
                "VENDOR\t" +
                "VENDOR_GRP\t" +
                "INVOICE_NO\t" +
                "TAX_NO\t" +
                "PAYMENT_TERM\t" +
                "PAYMENT_METHOD\t" +
                "PLAN_PAYMENT_DT\t" +
                "POSTING_DT\t" +
                "TOTAL_AMOUNT\t" +
                "DPP_AMOUNT\t" +
                "CURRENCY\t" +
                "TAX_CODE\t" +
                "HEADER TEXT\t" +
                "BANK_TYPE\t" +
                "gl_account\t" +
                "AMOUNT\t" +
                "COST_CENTER\t" +
                "WBS_ELEMENT\t" +
                "ITEM_TEXT\t" +
                "STATUS\t" +
                "SAP_DOC_NO\t" +
                "SAP_DOC_YEAR");
            foreach (var item in model)
            {
                if (item.Entity.PV_DATE != null)
                {
                    tb_r_record_generate_file record = new tb_r_record_generate_file();
                    record.generate_by = item.No_Reg.ToString();
                    record.group_code = item.Entity.PV_NO;

                    record.pv_date = DateTime.ParseExact(item.Entity.PV_DATE, "dd.MM.yyyy", CultureInfo.InvariantCulture);

                    record.trans_type = item.Entity.TRANS_TYPE;
                    record.vendor_code = item.Entity.VENDOR;
                    record.item_no = item.Entity.ITEM_NO.ToString();
                    record.generate_date = DateTime.Now;

                    await InsertData.RecordGenerateFile(record);

                    MANDT = (item.Entity.MANDT == null) ? "" : item.Entity.MANDT.ToString();
                    PV_NO = (item.Entity.PV_NO == null) ? "" : item.Entity.PV_NO;
                    PV_YEAR = (item.Entity.PV_YEAR == null) ? "" : item.Entity.PV_YEAR.ToString();
                    ITEM_NO = item.Entity.ITEM_NO.ToString();
                    PV_DATE = (item.Entity.PV_DATE == null) ? "" : item.Entity.PV_DATE;
                    PV_TYPE = item.Entity.PV_TYPE.ToString();
                    TRANS_TYPE = (item.Entity.TRANS_TYPE == null) ? "" : item.Entity.TRANS_TYPE.ToString();
                    VENDOR = (item.Entity.VENDOR == null) ? "" : item.Entity.VENDOR.ToString();
                    VENDOR_GRP = item.Entity.VENDOR_GRP.ToString();
                    INVOICE_NO = (item.Entity.INVOICE_NO == null) ? "" : item.Entity.INVOICE_NO;
                    TAX_NO = (item.Entity.TAX_NO == null) ? "" : item.Entity.TAX_NO;
                    PAYMENT_TERM = (item.Entity.PAYMENT_TERM == null) ? "" : item.Entity.PAYMENT_TERM;
                    PAYMENT_METHOD = (item.Entity.PAYMENT_METHOD == null) ? "" : item.Entity.PAYMENT_METHOD;
                    PLAN_PAYMENT_DT = (item.Entity.PLAN_PAYMENT_DT == null) ? "" : item.Entity.PLAN_PAYMENT_DT;
                    POSTING_DT = (item.Entity.POSTING_DT == null) ? "" : item.Entity.POSTING_DT.ToString();
                    TOTAL_AMOUNT = (item.Entity.TOTAL_AMOUNT == null) ? "" : item.Entity.TOTAL_AMOUNT.ToString();
                    DPP_AMOUNT = item.Entity.DPP_AMOUNT.ToString();
                    CURRENCY = (item.Entity.CURRENCY == null) ? "" : item.Entity.CURRENCY;
                    TAX_CODE = (item.Entity.TAX_CODE == null) ? "" : item.Entity.TAX_CODE;

CONTRAST_WEB/CONTRAST_WEB/Views/GenerateFile/Index.cshtml
@*@model IList<CONTRAST_WEB.Models.GenerateFileHelper>*@
@model PagedList.IPagedList<CONTRAST_WEB.Models.GenerateFileHelper>
@using PagedList.Mvc;
@{
    ViewBag.Title = "PARTICIPANT";
    Layout = "~/Views/Shared/_LayoutLg.cshtml";
    DateTime temp = DateTime.Now;
}
<div style="height:100px; padding:60px 0 0 0;" class="well navbar-fixed-top">
    <ol class="breadcrumb">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <button type="submit" style="border:0px; margin:0; background-color:transparent; padding:0px; color:dimgrey">Home</button>
            }
        </li>
        <li class="breadcrumb-item active">Generate File</li>
    </ol>
</div>
<div class="container">
        <div style="margin-top:110px;" id="products" class="row list-group _3EibU">
            <label style="width:100%;" class="h5sl">Generate File</label>
            <div class="h5a" style="margin:0px;">
            @using (Html.BeginForm("Index", "GenerateFile", FormMethod.Get, new { @class = "navbar-form navbar-left", style = "width:1100px;margin-top:0px;" }))
            {
                <div class="col-lg-2">
                    <h5 class="h5a" style="margin-bottom:5px;">Find by : </h5>
                    @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "width:200px", placeholder = "BTA, NAME" })
                </div>
                <div class="col-lg-2 col-lg-offset-1">
                    <h5 class="h5a" style="margin-bottom:5px;">Find by : </h5>
                    @Html.TextBox("SearchString2", ViewBag.CurrentFilter2 as string, new { @class = "form-control", style = "width:300px", placeholder = "Destination, Vendor, Budget, Travel Type" })
                </div>
                <div class="col-lg-4 col-lg-offset-2">
                    <h5 class="h5a" style="margin-bottom:5px;">Approve Date Range :</h5>
        
                    @if (ViewBag.startdate != null)
                    {
                        <span>@Html.TextBox("startdate", ViewBag.startdate as DateTime?, new { @class = "form-control", style = "width:160px", @id = "startdate", @type = "date", @Value = ViewBag.startdate.ToString("yyyy-MM-dd") })</span>
                    }
                    else
                    {
                        <span>@Html.TextBox("startdate", ViewBag.startdate as DateTime?, new { @class = "form-control", style = "width:160px", @id = "startdate", @type = "date" })</span>
                    }
                    @if (ViewBag.enddate != null)
                    {
                        <span>@Html.TextBox("enddate", ViewBag.enddate as DateTime?, new { @class = "form-control", style = "width:160px", @id = "enddate", @type = "date", @Value = ViewBag.enddate.ToString("yyyy-MM-dd") })</span>
                    }
                    else
                    {
                        <span>@Html.TextBox("enddate", ViewBag.enddate as DateTime?, new { @class = "form-control", style = "width:160px", @id = "enddate", @type = "date" })</span>
                    }
                </div>
                <div class="col-lg-1"><input style="margin-top:30px;width:110px;" type="submit" value="Search" class="btn btn-success btn-lg" /></div>
            }
                </div>
            <div class="well">
                @using (Html.BeginForm("Generate", "GenerateFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div style="width:100%;text-align:left;height:380px;overflow-y:scroll;border:0px;" class="clearfix">
                        <div style="padding:0 5px">
                            <table style="width:1800px;" class="table table-condensed table-striped">
                                <tr style="background-color:deepskyblue; text-align:center;">
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        BTA NUMBER
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        EMPLOYEE NAME
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        DESTINATION
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        VENDOR NAME
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        BUDGET
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        TOTAL AMOUNT
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        COST CENTER
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        WBS ELEMENT
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        TRAVEL TYPE
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        APPROVE DATE
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        BTR DATE
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        PLAN PAYMENT DATE
                                    </th>
                                    <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                        PAYMENT METHOD
                                    </th>
                                </tr>

                                @for (int k = 0; k < Model.Count(); k++)
                                {                                    
                                    <tr class="table-responsive">
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.BTR_NO)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.EMPLOYEE_NAME)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.DESTINATION)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.VENDOR_NAME)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.BUDGET)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.TOTAL_AMOUNT_)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.COST_CENTER_)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.WBS_ELEMENT_)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.TRAVEL_TYPE)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.PV_DATE)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.BTR_DATE)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.PLAN_PAYMENT_DATE)
                                        </td>
                                        <td style="width:auto;" class="td">
                                            @Html.DisplayFor(Model => Model[k].Entity.PAYMENT_METHOD_)
                                        </td>
                                    </tr>

                                }
                            </table>
                        </div>
                    @foreach (int item in ViewBag.id_data)
                    {
                        @Html.Hidden("id_data", item)
                    }
                    </div>
                   
                    <div id="show" style="margin:0px;padding:0px;" class="alert alert-success col-lg-12" hidden>
                        <strong>Success!</strong> Check File Download on Folder.
                    </div>
                    <div style="float:right;margin-top:10px;margin-left:100px;" class="col-lg-2">
                        <button id="button" class="btn btn-info btn-lg" type="submit" name="Submit" value="Submit"><span class="glyphicon glyphicon-download"></span>&nbsp;Download</button>
                    </div>
                }
                <div style="float:left;" class="col-lg-5">
                
                @if (ViewBag.startdate != null || ViewBag.enddate != null)
                {
                    <div class="h5a">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                </div>
                    <div style="height:5px;">
                        @Html.PagedListPager(Model, page => Url.Action("Index",
                                  new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilter2 = ViewBag.CurrentFilter2, startdate = ViewBag.startdate, enddate = ViewBag.enddate}))
                    </div>
                }
                else
                {
                    <div class="h5a">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                </div>
                    <div style="height:5px;">
                        @Html.PagedListPager(Model, page => Url.Action("Index",
                                             new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, currentFilter2 = ViewBag.CurrentFilter2}))
                    </div>
                }

                </div>
            </div>
            
        </div>
    </div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $("#button").click(function () {
            $("#show").fadeIn();
        });
    });
</script>