CONTRAST_WEB/CONTRAST_WEB/Controllers/PaymentProposalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using CONTRAST_WEB.Models;
using System.IO;
using System.Globalization;
using ClosedXML.Excel;
using System.Security.Claims;
using PagedList;

namespace CONTRAST_WEB.Controllers
{
    public class PaymentProposalController : Controller
    {
        //GET: PaymentProposal
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page, DateTime? startdate, DateTime? enddate)
        {
            var identity = (ClaimsIdentity)User.Identity;
            string[] claims = identity.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
            ViewBag.Privillege = claims;
            tb_m_employee model = await GetData.EmployeeInfo(identity.Name);

            List<PaymentProposalHelper> Generate = new List<PaymentProposalHelper>();
            List<vw_payment_proposal> data = new List<vw_payment_proposal>();
            data = await GetData.PaymentProposalData();

            foreach (var item in data)
            {
                PaymentProposalHelper temp = new PaymentProposalHelper();
                temp.Entity = item;
                temp.Name = model.name;
                temp.No_Reg = Convert.ToInt32(model.code);
                Generate.Add(temp);
            }


            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            if (startdate != null)
                ViewBag.startdate = startdate;
            else
                ViewBag.startdate = null;

            if (enddate != null)
                ViewBag.enddate = enddate;
            else
                ViewBag.enddate = null;

            //filter
            if (!String.IsNullOrEmpty(searchString))
            {
                List<PaymentProposalHelper> temp = new List<PaymentProposalHelper>();
                for (int k = 0; k < Generate.Count; k++)
                {
                    if ((Generate[k].Entity.vendor_code != null ? Generate[k].Entity.vendor_code : "").ToLower().Contains(searchString.ToLower()) ||
                        (Generate[k].Entity.currency != null ? Generate[k].Entity.currency : "").ToLower().Contains(searchString.ToLower()) ||
                        (Generate[k].Entity.beneficiary_name != null ? Generate[k].Entity.beneficiary_name : "").ToLower().Contains(searchString.ToLower()) ||
                        (Generate[k].Entity.account_number != null ? Generate[k].Entity.account_number : "").ToLower().Contains(searchString.ToLower()) ||
                        (Generate[k].Entity.employee_name != null ? Generate[k].Entity.employee_name : "").ToLower().Contains(searchString.ToLower()) ||
                        (Generate[k].Entity.refference != null ? Generate[k].Entity.refference : "").ToLower().Contains(searchString.ToLower()))
                    {
                        temp.Add(Generate[k]);
                    }
                }
                if (temp.Count() > 0) Generate = temp;
                else Generate = temp;
            }

            int pageSize = 15;
            int pageNumber = (page ?? 1);

            List<int> id_data = new List<int>();
            for (int k = 0; k < Generate.Count; k++)
                id_data.Add(Generate[k].Entity.id_data);
            ViewBag.id_data = id_data;
            return View("Index", Generate.OrderBy(b => b.Entity.vendor_code).ToList().ToPagedList(pageNumber, pageSize));
            
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Generate(List<int> id_data)
        {
            var identity = (ClaimsIdentity)User.Identity;
            string[] claims = identity.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
            ViewBag.Privillege = claims;
            tb_m_employee employee = await GetData.EmployeeInfo(identity.Name);

            List<PaymentProposalHelper> model = new List<PaymentProposalHelper>();
            for (int k = 0; k < id_data.Count(); k++)
            {
                model.Add(new PaymentProposalHelper());
                model[k].Entity = await GetData.PaymentProposal(id_data[k]);
                model[k].Name = employee.name.Trim();
                model[k].No_Reg = Convert.ToInt32(employee.code);
            }
            
            XLWorkbook CreateExcell = new XLWorkbook();
            var ExcelData = CreateExcell.Worksheets.Add("Payment Proposal");

            ExcelData.Cell(1, 1).Value = "ID_DATA";
            ExcelData.Cell(1, 2).Value = "VENDOR_CODE";
            ExcelData.Cell(1, 3).Value = "CURRENCY";
            ExcelData.Cell(1, 4).Value = "TOTAL_AMOUNT";
            ExcelData.Cell(1, 5).Value = "BENEFICIARY_NAME";
            ExcelData.Cell(1, 6).Value = "ACCOUNT_NUMBER";
            ExcelData.Cell(1, 7).Value = "EMPLOYEE_NAME";
            ExcelData.Cell(1, 8).Value = "REFFERENCE";

            int gap = 0;
            for (int i = 0; i < model.Count(); i++)
            {
                ExcelData.Cell(i + 2, 1).Value = model[i].Entity.id_data;
                ExcelData.Cell(i + 2, 2).Value = model[i].Entity.vendor_code;
                ExcelData.Cell(i + 2, 3).Value = model[i].Entity.currency;
                ExcelData.Cell(i + 2, 4).Value = model[i].Entity.total_amount;
                ExcelData.Cell(i + 2, 5).Value = model[i].Entity.beneficiary_name;
                ExcelData.Cell(i + 2, 6).Value = model[i].Entity.account_number;
                ExcelData.Cell(i + 2, 7).Value = model[i].Entity.employee_name;
                ExcelData.Cell(i + 2, 8).Value = model[i].Entity.refference;

                gap = i;
            }

            ExcelData.Cell(gap + 5, 5).Value = "Approved";
            ExcelData.Cell(gap + 5, 7).Value = "Reviewed";
            ExcelData.Cell(gap + 5, 9).Value = "Prepare";
            ExcelData.Cell(gap + 10, 5).Value = "Keijiro Inada";
            ExcelData.Cell(gap + 10, 6).Value = "Darmawan Widjaja";
            ExcelData.Cell(gap + 10, 7).Value = "Ronny K";
            ExcelData.Cell(gap + 10, 8).Value = "Yesse VH";
            ExcelData.Cell(gap + 10, 9).Value = "Sabid Ismulani";

            foreach (var item in model)
            {
                tb_r_record_payment_proposal record = new tb_r_record_payment_proposal();
                record.id_data = item.Entity.id_data;
                record.vendor_code = item.Entity.vendor_code;
                record.currency = item.Entity.currency;
                record.total_amount = item.Entity.total_amount;
                record.beneficiary_name = item.Entity.beneficiary_name;
                record.account_number = item.Entity.account_number;
                record.employee_name = item.Entity.employee_name;
                record.refference = item.Entity.refference;
                record.generate_by = model[0].No_Reg.ToString();
                record.generate_date = DateTime.Now;

                await InsertData.RecordPaymentProposal(record);
            }

            MemoryStream excelStream = new MemoryStream();
            CreateExcell.SaveAs(excelStream);
            excelStream.Position = 0;
            return File(excelStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Payment Proposal.xlsx");
            
        }
    }
}

CONTRAST_WEB/CONTRAST_WEB/Views/PaymentProposal/index.cshtml
@*@model IList<CONTRAST_WEB.Models.PaymentProposalHelper>*@
@model PagedList.IPagedList<CONTRAST_WEB.Models.PaymentProposalHelper>
@using PagedList.Mvc;
@{
    ViewBag.Title = "PARTICIPANT";
    Layout = "~/Views/Shared/_LayoutLg.cshtml";
    DateTime temp = DateTime.Now;
}
<div style="height:100px; padding:60px 0 0 0;" class="well navbar-fixed-top">
    <ol class="breadcrumb">
        <li>
            @using (Html.BeginForm("Index", "Home"))
            {
                <button type="submit" style="border:0px; margin:0; background-color:transparent; padding:0px; color:dimgrey">Home</button>
            }
        </li>
        <li class="breadcrumb-item active">Payment Proposal</li>
    </ol>
</div>

<div class="container">
    <div style="margin-top:115px;" id="products" class="row list-group _3EibU">
        <label style="width:100%" class="h5sl">Payment Proposal</label>
        <div class="col-sm-12 col-md-10">
            <div>
                <div class="collapse navbar-collapse">
                    @using (Html.BeginForm("Index", "PaymentProposal", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                    {
                        <table>
                            <tr>
                                <td>
                                    Search: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", style = "width:200px", placeholder = "" })
                                </td>
                                <!--<td>
                                                @if (ViewBag.startdate != null)
                                        {
                                            @Html.TextBox("startdate", ViewBag.startdate as DateTime?, new { @id = "startdate", @type = "date", @Value = ViewBag.startdate.ToString("yyyy-MM-dd") })
                                }
                                else
                                {
                                    @Html.TextBox("startdate", ViewBag.startdate as DateTime?, new { @id = "startdate", @type = "date" })
                                }
                                            </td>

                                            <td>
                                                @if (ViewBag.enddate != null)
                                        {
                                            @Html.TextBox("enddate", ViewBag.enddate as DateTime?, new { @id = "enddate", @type = "date", @Value = ViewBag.enddate.ToString("yyyy-MM-dd") })
                                }
                                else
                                {
                                    @Html.TextBox("enddate", ViewBag.enddate as DateTime?, new { @id = "enddate", @type = "date" })
                                }
                                            </td>-->
                                <td>
                                    <input type="submit" value="Search" class="btn btn-success" />
                                </td>
                            </tr>
                        </table>
                    }
                </div>
            </div>
        </div>

        <div class="well">
            @using (Html.BeginForm("Generate", "PaymentProposal", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div style="width:100%;text-align:left;height:380px;overflow-y:scroll;border:0px;" class="clearfix">

                    <div style="padding:0 5px">
                        <table style="width:1450px;" class="table table-condensed table-striped">
                            <tr style="background-color:deepskyblue; text-align:center;">
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    ID_DATA
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    VENDOR_CODE
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    CURRENCY
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    TOTAL_AMOUNT
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    BENEFICIARY_NAME
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    ACCOUNT_NUMBER
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:center; border-right:1px solid white;">
                                    EMPLOYEE_NAME
                                </th>
                                <th style="color:white; background-color:deepskyblue; text-align:left; border-right:1px solid white;">
                                    REFFERENCE
                                </th>
                            </tr>

                            @for (int k = 0; k < Model.Count(); k++)
                            {

                                @Html.HiddenFor(Model => Model[k].No_Reg)
                                @Html.HiddenFor(Model => Model[k].Name)
                                @Html.HiddenFor(Model => Model[k].Entity.id_data)
                                @Html.HiddenFor(Model => Model[k].Entity.vendor_code)
                                @Html.HiddenFor(Model => Model[k].Entity.currency)
                                @Html.HiddenFor(Model => Model[k].Entity.total_amount)
                                @Html.HiddenFor(Model => Model[k].Entity.beneficiary_name)
                                @Html.HiddenFor(Model => Model[k].Entity.account_number)
                                @Html.HiddenFor(Model => Model[k].Entity.employee_name)
                                @Html.HiddenFor(Model => Model[k].Entity.refference)

                                <tr class="table-responsive">
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.id_data)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.vendor_code)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.currency)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.total_amount)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.beneficiary_name)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.account_number)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.employee_name)
                                    </td>
                                    <td style="width:auto;" class="td">
                                        @Html.DisplayFor(Model => Model[k].Entity.refference)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    @foreach (int item in ViewBag.id_data)
                    {
                        @Html.Hidden("id_data", item)
                    }
                </div>

                <div id="show" style="margin:0px;padding:0px;" class="alert alert-success col-lg-12" hidden>
                    <strong>Success!</strong> Check File Download on Folder.
                </div>
                <div style="float:right;margin-top:15px;margin-left:100px;" class="col-lg-offset-2">
                    <button id="button" class="btn btn-info btn-lg" type="submit" name="Submit" value="Submit"><span class="glyphicon glyphicon-download"></span>&nbsp;Download</button>
                </div>
            }
            <div style="float:left; margin-top:1px" " class="col-lg-offset-0">

                @if (ViewBag.startdate != null || ViewBag.enddate != null)
                {
                    <div class="h5a">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    </div>
                    <div style="height:5px;">
                        @Html.PagedListPager(Model, page => Url.Action("Index",
                                                 new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, startdate = ViewBag.startdate, enddate = ViewBag.enddate }))
                    </div>
                }
                else
                {
                    <div class="h5a">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    </div>
                    <div style="height:5px;">
                        @Html.PagedListPager(Model, page => Url.Action("Index",
                                                            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                }
            </div>
        </div>

    </div>
</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $("#button").click(function () {
            $("#show").fadeIn();
        });
    });
</script>