CONTRAST_WEB/CONTRAST_WEB/Controllers/SettlementListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CONTRAST_WEB.Models;
using System.Net.Http.Headers;
using System.Net.Http;
using Newtonsoft.Json;
using System.IO;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using PdfSharp;
using PdfSharp.Drawing.Layout;
using CONTRAST_WEB.CustomValidator;
using CONTRAST_WEB.Models;
using CONTRAST_WEB.Helper;
using System.Security.Claims;


namespace CONTRAST_WEB.Controllers
{
    public class SettlementListController : Controller
    {

        public async Task<SettlementHelper> Sum(SettlementHelper model)
        {
            TimeSpan duration = ((DateTime)model.End_Extend - (DateTime)model.Start_Extend);
            var rank = await GetData.EmployeeInfo(model.TravelRequest.no_reg.ToString());

            //var diff = (model.End_Extend - model.Start_Extend);
            var meal_platform = await GetData.Procedures(rank.@class);
            if (model.halfday_flag1 == true && (DateTime)model.End_Extend == (DateTime)model.Start_Extend)
            {
                model.MealSettlement = (float)meal_platform.meal_allowance / 2;
            }
            else if (model.halfday_flag1 == true)
            {
                model.MealSettlement = (float)meal_platform.meal_allowance * Convert.ToInt32(duration.Days) + (float)meal_platform.meal_allowance / 2;
            }
            else
            {
                model.MealSettlement = (float)meal_platform.meal_allowance * Convert.ToInt32(duration.Days);
            }
            //model.MealSettlement = (float)meal_platform.meal_allowance * Convert.ToInt32(duration.Days);
            //ModelState.Remove(ModelState.FirstOrDefault(m => m.Key.ToString().StartsWith("MealSettlement")));
            return (model);
        }

        public async Task<SettlementHelper> Sum2(SettlementHelper model)
        {
            var rank = await GetData.EmployeeInfo(model.TravelRequest.no_reg.ToString());

            var meal_platform = await GetData.Procedures(rank.@class);
            if (model.halfday_flag1 & model.halfday_flag2 == true)
            {
                model.MealSettlement = (float)meal_platform.meal_allowance;
            }
            else if (model.halfday_flag1 | model.halfday_flag2 == true)
            {
                model.MealSettlement = (float)meal_platform.meal_allowance / 2;
            }
            else
            {
                model.MealSettlement = 0;
            }

            return (model);
        }

        public async Task<JsonResult> GetSearchValue(string search, string code)
        {
            List<Class1> list = new List<Class1>();
            list = await GetData.SearchName(search);
            List<Class1> filtered = new List<Class1>();
            foreach (var item in list)
            {
                if (!item.code.Contains(code)) filtered.Add(item);
            }

            return new JsonResult { Data = filtered, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public async Task<JsonResult> GetSearchValue2(string search, string code)
        {

            List<Class1> list = new List<Class1>();
            list = await GetData.SearchNameDiv(search);
            //list = await GetData.SearchName(search);
            List<Class1> filtered = new List<Class1>();
            foreach (var item in list)
            {
                if (!item.code.Contains(code)) filtered.Add(item);
            }

            return new JsonResult { Data = filtered, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        // GET: SettlementList
        [HttpPost]
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(string applied)
        {
            var identity = (ClaimsIdentity)User.Identity;
            string[] claims = identity.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
            ViewBag.Privillege = claims;

            tb_m_employee model = new tb_m_employee();

            if (applied != null) model = await GetData.EmployeeInfo(applied);
            else model = await GetData.EmployeeInfo(identity.Name);

            tb_m_employee logged = await GetData.EmployeeInfo(identity.Name);

            ViewBag.loged_id = logged.code.Trim();
            ViewBag.loged_name = logged.name.Trim(' ');

            ViewBag.applied_name = model.name.Trim();

            ViewBag.Employee = model;
            ViewBag.applied = model.code.Trim();

            List<vw_travel_for_settlement> ResponseList = new List<vw_travel_for_settlement>();
            List<vw_rejected_travel_for_settlement> RejectList = new List<vw_rejected_travel_for_settlement>();
            ResponseList = await GetData.TravelSettlementList(Convert.ToInt32(model.code));
            RejectList = await GetData.RejectTravelSettlementList(Convert.ToInt32(model.code));
            int k = ResponseList.Count;
            for (int i = 0; i < ResponseList.Count(); i++)
            {
                ResponseList[i].login_id = model.code;
                ResponseList[i].final_status = "0";
                ResponseList[i].comment = "";
                ResponseList[i].process_reject = "";
                k++;
            }

            foreach (var item in RejectList)
            {
                vw_travel_for_settlement temp = new vw_travel_for_settlement();
                temp.comment = item.comment != null ? item.comment : "No Comment";
                temp.destination_name = item.destination_name;
                temp.emp_name = item.emp_name;
                temp.end_date = item.end_date;
                temp.final_status = item.final_status;
                temp.grand_total_settlement = item.grand_total_settlement;
                temp.group_code = item.group_code;
                temp.id_destination_city = item.id_destination_city;
                temp.id_request = item.id_request;
                temp.login_id = model.code;
                temp.no_reg = item.no_reg;
                temp.process_reject = item.process_reject;
                temp.start_date = item.start_date;
                temp.total_hotel = item.total_hotel;
                temp.total_laundry = item.total_laundry;
                temp.total_meal = item.total_meal;
                temp.total_miscellaneous = item.total_miscellaneous;
                temp.total_preparation = item.total_preparation;
                temp.total_ticket = item.total_ticket;
                temp.total_transportation = item.total_transportation;
                temp.total_winter = item.total_winter;
                ResponseList.Add(temp);
            }
            return View(ResponseList);
        }


        [HttpPost]
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        [ValidateAntiForgeryToken]
        [NoCache]
        public async Task<ActionResult> Details(vw_travel_for_settlement model)
        {
            string time = "";
            ViewBag.time2 = time;
            SettlementHelper Settlement = new SettlementHelper();
            Settlement.TravelRequest = model;
            Settlement.extend_flag = true;
            Response.Cache.SetNoStore();
            return View(Settlement);
        }

        [HttpPost]
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        [ValidateAntiForgeryToken]
        [NoCache]
        public async Task<ActionResult> Insert(SettlementHelper model, string sum, string insert, string time11, string time2)
        {
            if (ModelState.IsValid)
            {
                ViewBag.time11 = time11;
                ViewBag.time2 = time2;

                if (time11 != null)
                {
                    model.date_depart = time11;
                }

                if (time2 != null)
                {
                    model.date_return = time2;
                }


                if (insert != null)
                {
                    if (Request.Files["UploadedFile1"] != null)
                    {
                        HttpPostedFileBase file = Request.Files["UploadedFile1"];
                        model.ReceiptFileTransportation = file;
                    }
                    if (Request.Files["UploadedFile2"] != null)
                    {
                        HttpPostedFileBase file = Request.Files["UploadedFile2"];
                        model.ReceiptFileLaundry = file;
                    }
                    if (Request.Files["UploadedFile3"] != null)
                    {
                        HttpPostedFileBase file = Request.Files["UploadedFile3"];
                        model.ReceiptFileOther = file;
                    }

                    await UpdateData.RejectedClearance(model.TravelRequest.group_code);

                    tb_r_travel_actualcost ActualCostObject = new tb_r_travel_actualcost();
                    ActualCostObject.information_actualcost = "Settlement";
                    ActualCostObject.end_date_extend = model.End_Extend;
                    ActualCostObject.start_date_extend = model.Start_Extend;
                    ActualCostObject.user_created = model.TravelRequest.no_reg.ToString();
                    ActualCostObject.additional1 = model.halfday_flag1.ToString();
                    ActualCostObject.additional2 = model.halfday_flag2.ToString();
                    ActualCostObject.additional3 = model.date_depart;
                    ActualCostObject.additional4 = model.date_return;


                    List<tb_m_vendor_employee> bankName = new List<tb_m_vendor_employee>();

                    bankName = await GetData.VendorEmployee((model.TravelRequest.no_reg));

                    ActualCostObject.vendor_code = bankName[0].vendor_code_employee;

CONTRAST_WEB/CONTRAST_WEB/Views/SettlementList/Done.cshtml
@{
    ViewBag.Title = "Done";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .centerAllign {
        margin: auto;
        width: 50%;
        padding: 10px;
    }
</style>

<div style="padding-top:100px">
    <table style="font-size:30px; border:none" class="centerAllign">
        <tr>
            <td style="text-align:center">
                <strong style="color:#ff0000;text-align:justify">@ViewBag.Done</strong>
            </td>
        </tr>
        <tr>
            <td style="text-align:center">
                already been settled
            </td>
        </tr>
    </table>
    
</div>
<meta http-equiv="refresh" content="3;url=@ViewBag.URL" name="applied" />

CONTRAST_WEB/CONTRAST_WEB/Views/SettlementList/Index.Mobile.cshtml
@model IList<CONTRAST_WEB.Models.vw_travel_for_settlement>

@{
    ViewBag.Title = "TRAVEL SETTLEMENT";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}

<div class="container">
    <div style="margin-top:70px;" id="products" class="row list-group _3EibU">
        @for (var i = 0; i < Model.Count; i++)
        {
            var item = Model[i];

            using (Html.BeginForm("Details", "SettlementList", Model[i]))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => item.id_request)
                @Html.HiddenFor(m => item.id_destination_city)
                @Html.HiddenFor(m => item.total_meal)
                @Html.HiddenFor(m => item.total_miscellaneous)
                @Html.HiddenFor(m => item.total_ticket)
                @Html.HiddenFor(m => item.total_transportation)
                @Html.HiddenFor(m => item.total_winter)
                @Html.HiddenFor(m => item.total_hotel)
                @Html.HiddenFor(m => item.total_laundry)
                @Html.HiddenFor(m => item.no_reg)
                @Html.HiddenFor(m => item.emp_name)
                @Html.HiddenFor(m => item.group_code)
                @Html.HiddenFor(m => item.login_id)
                @Html.HiddenFor(m => item.comment)
                @Html.HiddenFor(m => item.final_status)
                @Html.HiddenFor(m => item.process_reject)
                <div class="item col-xs-12">
                <div class="thumbnail">
                    <div class="clearfix">
                            <div style="margin-right:15px;" class="column content">
                                <span style="padding:0 10px"><input type="image" img style="margin-top:5px; width:auto; height:50px" src="~/img/Settlement-icon-b.png" /></span>
                            </div>

                            <div style="width:110px;" class="column menu">
								<div>
                                <span class="templatetext">@Html.DisplayFor(modelItem => item.group_code)</span>
								</div>
								<div>
                                <span class="designationstyle">(to @Html.DisplayFor(modelItem => item.destination_name) )</span>
								</div>
								<div>
                                @if (item.final_status == "2")
                                {
                                    <strong style="color:red">Rejected</strong>
                                }
                                else if (item.final_status == "0")
                                {
                                    <strong style="color:darkcyan">Pending</strong>
                                }
								</div>
                            </div>

                            <span style="float:right; padding:20px 20px;" class="glyphicon glyphicon-chevron-right"></span>
                        </div>
                    </div>
                </div>
            }
        }

    </div>
</div>    
        

<script>
        function goBack() {
            window.history.back();
        }
</script>

CONTRAST_WEB/CONTRAST_WEB/Views/SettlementList/Index.cshtml
@model IList<CONTRAST_WEB.Models.vw_travel_for_settlement>
@{
	ViewBag.Title = "SETTLEMENT LIST";
	Layout = "~/Views/Shared/_LayoutLg.cshtml";
}
<div style="height:100px; padding:60px 0 0 0;" class="well navbar-fixed-top">
	<ol class="breadcrumb">
		<li>
			@using (Html.BeginForm("Index", "Home"))
			{
				<button type="submit" style="border:0px; margin:0; background-color:transparent; padding:0px; color:dimgrey">Home</button>
			}
		</li>
		<li class="breadcrumb-item active">Settlement List</li>
	</ol>
</div>
<div class="container">
	<div style="margin-top:110px; padding:0 90px;" id="products" class="row list-group _3EibU">
		@using (Html.BeginForm("Index", "SettlementList", FormMethod.Post, new { enctype = "multipart/form-data" }))
		{
			@Html.AntiForgeryToken()
			foreach (var item in ViewBag.Privillege)
			{
				if (item == "contrast.travelcoordinator")
				{
				<div style="width:960px;" class="col-md-11 ">
					<hr>
				</div>
				<div style="width:950px;text-align:center" class="col-md-11" >
					<div style="margin:5px;" class="form-group form-inline">
						<strong style="color:deepskyblue;">TRAVEL COORDINATOR :</strong> @ViewBag.loged_name (@ViewBag.loged_id)
					</div>
				</div> 
				<div style="width:475px;" class="col-md-5">
					<div style="margin:5px;" class="form-group form-inline">
						Type name Employee :
						<input type="text" id="searchInput2" name="applied" class="form-control" style="width:200px" value=@ViewBag.applied />
						<input type="text" id="code" name="code" value=@ViewBag.applied hidden>
						<button type="submit" class="btn btn-success btn-lg input-group-btn" name="Add" value="Submit" style="width:70px">Assign</button>
					</div>
				</div>

				 <div style="width:475px;padding-top:5px" class="col-md-5">
					<div style="margin:5px;" class="form-group form-inline">
						Assigned Employee :
						@if (ViewBag.applied_name != null)
						{
							<label>@ViewBag.applied_name (@ViewBag.applied)</label>
						}
					</div>
				</div>

				<div style="width:960px;" class="col-md-11 ">
					<hr>
				</div>
				}
			}
		}
		@for (var i = 0; i < Model.Count; i++)
		{
			var item = Model[i];

			using (Html.BeginForm("Details", "SettlementList", Model[i]))
			{
				@Html.AntiForgeryToken()
				@Html.HiddenFor(m => item.id_request)
				@Html.HiddenFor(m => item.id_destination_city)
				@Html.HiddenFor(m => item.total_meal)
				@Html.HiddenFor(m => item.total_miscellaneous)
				@Html.HiddenFor(m => item.total_ticket)
				@Html.HiddenFor(m => item.total_transportation)
				@Html.HiddenFor(m => item.total_winter)
				@Html.HiddenFor(m => item.total_hotel)
				@Html.HiddenFor(m => item.total_laundry)
				@Html.HiddenFor(m => item.no_reg)
				@Html.HiddenFor(m => item.emp_name)
				@Html.HiddenFor(m => item.group_code)
				@Html.HiddenFor(m => item.login_id)
				@Html.HiddenFor(m => item.comment)
				@Html.HiddenFor(m => item.final_status)
				@Html.HiddenFor(m => item.process_reject)
				<div class="item col-xs-6 col-lg-6">
					<div class="thumbnail">
						<div class="clearfix">
							<div class="column content">
								<span style="padding:0 10px"><input type="image" img style="margin:5px 0px; width:auto; height:50px" src="~/img/Settlement-icon-b.png" /></span>
							</div>
							<div style="padding:20px 1px; width:270px;" class="column menu">
								<span class="templatetext">@Html.DisplayFor(modelItem => item.group_code)</span>
								<span class="designationstyle">&nbsp;(to @Html.DisplayFor(modelItem => item.destination_name) )</span>
								@if (item.final_status == "2")
								{
									<strong style="color:red">Rejected</strong>
								}
								else if (item.final_status == "0")
								{
									<strong style="color:darkcyan">Pending</strong>
								}
							</div>
							<span style="float:right; padding:20px 20px;" class="glyphicon glyphicon-chevron-right"></span>
						</div>
					</div>
				</div>
			}
		}
	</div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link href="~/Scripts/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>
<script>
	 $("#searchInput2").autocomplete({
		source: function (request, response) {
			$.ajax({
				url: '@Url.Action("GetSearchValue2", "SettlementList")',
				dataType: "json",
			data: { search: $("#searchInput2").val(), code: $("#code").val() },
				success: function (data) {
					response($.map(data, function (item) {
						return { label: item.name, value: item.code };
					}));
				},
				error: function (xhr, status, error) {
					alert("Error Has detected");
				}
			});
		}
	});

	function goBack() {
		window.history.back();
	}
</script>

CONTRAST_WEB/CONTRAST_WEB/Views/SettlementList/IndexMSTRMobile.cshtml
@model IList<CONTRAST_WEB.Models.vw_travel_for_settlement>

@{
    ViewBag.Title = "TRAVEL SETTLEMENT";
    Layout = "~/Views/Shared/_LayoutM.Mobile.cshtml";
}

<div class="container">
    <div style="margin-top:70px;" id="products" class="row list-group _3EibU">
        @for (var i = 0; i < Model.Count; i++)
        {
            var item = Model[i];

            using (Html.BeginForm("DetailsMSTR", "SettlementList", Model[i]))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => item.id_request)
                @Html.HiddenFor(m => item.id_destination_city)
                @Html.HiddenFor(m => item.total_meal)
                @Html.HiddenFor(m => item.total_miscellaneous)
                @Html.HiddenFor(m => item.total_ticket)
                @Html.HiddenFor(m => item.total_transportation)
                @Html.HiddenFor(m => item.total_winter)
                @Html.HiddenFor(m => item.total_hotel)
                @Html.HiddenFor(m => item.total_laundry)
                @Html.HiddenFor(m => item.no_reg)
                @Html.HiddenFor(m => item.emp_name)
                @Html.HiddenFor(m => item.group_code)
                @Html.HiddenFor(m => item.login_id)
                @Html.HiddenFor(m => item.comment)
                @Html.HiddenFor(m => item.final_status)
                @Html.HiddenFor(m => item.process_reject)
                <div class="item col-xs-12">
                <div class="thumbnail">
                    <div class="clearfix">
                            <div style="margin-right:15px;" class="column content">
                                <span style="padding:0 10px"><input type="image" img style="margin-top:5px; width:auto; height:50px" src="~/img/Settlement-icon-b.png" /></span>
                            </div>

                            <div style="width:110px;" class="column menu">
								<div>
                                <span class="templatetext">@Html.DisplayFor(modelItem => item.group_code)</span>
								</div>
								<div>
                                <span class="designationstyle">(to @Html.DisplayFor(modelItem => item.destination_name) )</span>
								</div>
								<div>
                                @if (item.final_status == "2")
                                {
                                    <strong style="color:red">Rejected</strong>
                                }
                                else if (item.final_status == "0")
                                {
                                    <strong style="color:darkcyan">Pending</strong>
                                }
								</div>
                            </div>

                            <span style="float:right; padding:20px 20px;" class="glyphicon glyphicon-chevron-right"></span>
                        </div>
                    </div>
                </div>
            }
        }

    </div>
</div>    
        

<script>
        function goBack() {
            window.history.back();
        }
</script>