CONTRAST_WEB/CONTRAST_WEB/Controllers/TravelStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CONTRAST_WEB.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.IO;
using PdfSharp.Pdf;
using PdfSharp.Drawing;
using PdfSharp;
using System.Security.Claims;

namespace CONTRAST_WEB.Controllers
{
    public class TravelStatusController : Controller
    {
        [Authorize]
        [Authorize(Roles = "contrast.user")]
        // GET: TravelStatus
        public async Task<ActionResult> Index()
        {
            var identity = (ClaimsIdentity)User.Identity;
            string[] claims = identity.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).ToArray();
            ViewBag.Privillege = claims;
            tb_m_employee model = await GetData.EmployeeInfo(identity.Name);

            List<vw_request_summary> ResponseList = new List<vw_request_summary>();
            ResponseList = await GetData.RequestSummaryListInfo(model.code);
            //check if there are travel status entry
            if (ResponseList.Count>0)ResponseList = ResponseList.OrderBy(x => x.group_code).ToList();
            List<string> apprv_name = new List<string>();
            List<DateTime> return_date = new List<DateTime>();

            List<int> travel_duration = new List<int>();

            for (int k = 0; k < ResponseList.Count(); k++)
            {
                if (ResponseList[k].apprv_flag_lvl20 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl20));
                else

                if (ResponseList[k].apprv_flag_lvl19 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl19));
                else

                if (ResponseList[k].apprv_flag_lvl18 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl18));
                else

                if (ResponseList[k].apprv_flag_lvl17 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl17));
                else

                if (ResponseList[k].apprv_flag_lvl16 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl16));
                else

                if (ResponseList[k].apprv_flag_lvl15 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl15));
                else

                if (ResponseList[k].apprv_flag_lvl14 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl14));
                else

                if (ResponseList[k].apprv_flag_lvl13 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl13));
                else

                if (ResponseList[k].apprv_flag_lvl12 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl12));
                else

                if (ResponseList[k].apprv_flag_lvl11 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl11));
                else
                if (ResponseList[k].apprv_flag_lvl10 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl10));
                else
                if (ResponseList[k].apprv_flag_lvl9 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl9));
                else
                if (ResponseList[k].apprv_flag_lvl8 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl8));
                else
                if (ResponseList[k].apprv_flag_lvl7 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl7));
                else
                if (ResponseList[k].apprv_flag_lvl6 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl6));
                else
                if (ResponseList[k].apprv_flag_lvl5 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl5));
                else
                if (ResponseList[k].apprv_flag_lvl4 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl4));
                else
                if (ResponseList[k].apprv_flag_lvl3 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl3));
                else
                if (ResponseList[k].apprv_flag_lvl2 != null)
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl2));
                else
                    apprv_name.Add(await GetData.EmployeeNameInfo(ResponseList[k].apprv_by_lvl1));


                if (ResponseList[k].endDate_3 != null)
                    return_date.Add(ResponseList[k].endDate_3 ?? default(DateTime));
                else
                if (ResponseList[k].endDate_2 != null)
                    return_date.Add(ResponseList[k].endDate_2 ?? default(DateTime));
                else
                if (ResponseList[k].endDate_1 != null)
                    return_date.Add(ResponseList[k].endDate_1 ?? default(DateTime));


                travel_duration.Add((ResponseList[k].duration_1 ?? default(int)) + (ResponseList[k].duration_2 ?? default(int)) + (ResponseList[k].duration_3 ?? default(int)));
            }

            ViewBag.ReturnDate = return_date;
            ViewBag.Username = model.name;
            ViewBag.Bossname = apprv_name;
            ViewBag.Duration = travel_duration;

            //save comment count
            List<int> msgcount = new List<int>();
            //save revised count
            List<bool> revise_flag = new List<bool>();
            
            for (int k = 0; k < ResponseList.Count(); k++)
            {
                //count new messages
                List<tb_r_travel_request_comment> comment = new List<tb_r_travel_request_comment>();
                comment = await GetData.Comment(ResponseList[k].group_code);
                if (comment.Count > 0)
                {
                    var newmsg = comment.Where(x => x.read_flag == false && x.no_reg_comment != ResponseList[k].no_reg);
                    msgcount.Add(newmsg.Count());
                }
                else
                    msgcount.Add(0);

                //check revised btr or not
                var request=await GetData.TravelRequestGCList(ResponseList[k].group_code);
                bool revise=false;
                for (int i = 0; i < request.Count(); i++)
                {
                    if (request[i].additional1 == "1")
                    {
                        revise = true;
                    }
                    
                }
                revise_flag.Add(revise);
            }
            ViewBag.newmsg = msgcount;
            ViewBag.reviseflag = revise_flag;
            
            return View(ResponseList);
        }


        [Authorize]
        [Authorize(Roles = "contrast.user")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Details(vw_request_summary model)
        {
            TravelStatusHelper model2 = new TravelStatusHelper();
            model2.travel_request = model;
            model2.participants = await GetData.TravelRequestParticipant(model2.travel_request);

            List<string> ModelList = new List<string>();
            for (int i = 0; i < model2.participants.Count(); i++)
            {
                ModelList.Add(await GetData.EmployeeNameInfo(model2.participants[i].no_reg));
            }
            ViewBag.RL = ModelList;

            List<string> apprv_name = new List<string>();
            List<string> apprv_status = new List<string>();

            string temp = "";
            string ttemp = "";
            for (int k = 0; k < 19; k++)
            {
                temp = null;
                ttemp = null;
                if (k == 19)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl20);
                    ttemp = model2.travel_request.apprv_flag_lvl20;
                }
                else
                if (k == 18)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl19);
                    ttemp = model2.travel_request.apprv_flag_lvl19;
                }
                else
                if (k == 17)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl18);
                    ttemp = model2.travel_request.apprv_flag_lvl18;
                }
                else
                if (k == 16)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl17);
                    ttemp = model2.travel_request.apprv_flag_lvl17;
                }
                else
                if (k == 15)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl16);
                    ttemp = model2.travel_request.apprv_flag_lvl16;
                }
                else
                if (k == 14)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl15);
                    ttemp = model2.travel_request.apprv_flag_lvl15;
                }
                else
                if (k == 13)
                {
                    temp = await GetData.EmployeeNameInfo(model2.travel_request.apprv_by_lvl14);

CONTRAST_WEB/CONTRAST_WEB/Views/TravelStatus/CommentMSTR.cshtml
@model List<CONTRAST_WEB.Models.tb_r_travel_request_comment>
@{
    ViewBag.Title = "DETAIL TRAVEL STATUS";
    Layout = "~/Views/Shared/_LayoutLg.cshtml";

}
<div class="container">
    <div style="margin-top:100px" class="row">
        <div class="col-md-8 col-md-offset-1"><h5 class="h5s">COMMENT FOR @ViewBag.group_code</h5></div>
        <div style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" class="col-md-10 col-md-offset-1">
            @for (int k = 0; k < Model.Count(); k++)
            {
                <h5 class="h5b" style="color:black; font-size:15px">
                    <b>@Html.DisplayFor(m => m[k].name)</b> 
                    <font color="grey" size="2">wrote at @Html.DisplayFor(m => m[k].create_date)</font>
                </h5>
                @Html.DisplayFor(m => m[k].comment, new { @readonly = "readonly" })
            }
        </div>
        
        @using (Html.BeginForm("AddCommentMSTR", "TravelStatus", FormMethod.Post))
        {
            <div class="col-md-8 col-md-offset-1" style="padding-top:20px;">              
                  @Html.AntiForgeryToken()
                  @Html.TextBox("commentbox", null, new { @class = "form-control", placeholder = "input comment here" })
                  @Html.Hidden("groupcode", (object)ViewBag.group_code)
                  @Html.Hidden("no_reg_to", (object)ViewBag.no_reg_to)
                  @Html.Hidden("noreg", (object)ViewBag.noreg)

            </div>
            <div class="col-md-2 "style="padding-top:20px;">
                <span><input type="submit" class="btn btn-info btn-sm" value="Submit" /></span>
                @*<span class="btn btn-sm btn-default">@Html.ActionLink("Back", "IndexMSTR")</span>*@
            </div>
        }
    </div>     
</div>

CONTRAST_WEB/CONTRAST_WEB/Views/TravelStatus/CommentMSTRMobile.cshtml
@model List<CONTRAST_WEB.Models.tb_r_travel_request_comment>
@{
    ViewBag.Title = "DETAIL TRAVEL STATUS";
    Layout = "~/Views/Shared/_LayoutM.Mobile.cshtml";

}

<div class="container">
    <div style="margin-top:70px" class="row">
        <div class="col-md-8 col-md-offset-1"><h5 class="h5s">COMMENT FOR @ViewBag.group_code</h5></div>


        <div style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" class="col-md-10 col-md-offset-1">
            @for (int k = 0; k < Model.Count(); k++)
            {
                <h5 class="h5b" style="color:black; font-size:15px">
                    <b>@Html.DisplayFor(m => m[k].name)</b>
                    <font color="grey" size="2px">wrote at @Html.DisplayFor(m => m[k].create_date)</font>
                </h5>

                @Html.DisplayFor(m => m[k].comment, new { @readonly = "readonly" })

            }
        </div>

        @using (Html.BeginForm("AddCommentMSTR", "TravelStatus", FormMethod.Post))
        {
            <div class="col-md-8 col-md-offset-1" style="padding-top:20px;">
                @Html.AntiForgeryToken()
                @Html.TextBox("commentbox", null, new { @class = "form-control", placeholder = "input comment here" })
                @Html.Hidden("groupcode", (object)ViewBag.group_code)
                @Html.Hidden("no_reg_to", (object)ViewBag.no_reg_to)
                @Html.Hidden("noreg", (object)ViewBag.noreg)

            </div>
            <div class="col-md-2 " style="padding-top:20px;">
                <input type="submit" class="btn btn-info btn-lg form-control" value="Submit" />
                @*<span class="btn btn-xs btn-default">@Html.ActionLink("Back", "IndexMSTR")</span>*@
            </div>
        }
    </div>
</div>

CONTRAST_WEB/CONTRAST_WEB/Views/TravelStatus/Details.Mobile.cshtml
@model CONTRAST_WEB.Models.TravelStatusHelper
@{
    ViewBag.Title = "DETAIL TRAVEL STATUS";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
    List<string> ModelList = new List<string>();
    ModelList = ViewBag.RL;
}

@using (Html.BeginForm("Drop", "TravelStatus", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.travel_request.group_code)
    <div class="container">
        <div style="margin-top:70px" class="row">
            <div class="col-xs-12"><h4 style="text-align:left;">DETAIL TRAVEL STATUS @Html.HiddenFor(m => m.travel_request.id_request)</h4></div>
            <form action="" id="loginForm">
                <div style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" class="col-xs-12">
                    <h5 class="h5a">No Reg :</h5>
                    @Html.DisplayFor(m => m.travel_request.no_reg, new { placeholder = "No Reg", @readonly = "readonly" })
                    <h5 class="h5a">Request Purpose :</h5>
                    @Html.DisplayFor(m => m.travel_request.travel_purpose, new { placeholder = "Departure", @readonly = "readonly" })
                    <h5 class="h5a">Reason of Assignment :</h5>
                    @Html.DisplayFor(m => m.travel_request.reason_of_assigment, new { placeholder = "Reason Assigment", @readonly = "readonly" })
                    <h5 class="h5a">Request Type :</h5>
                    @Html.TextBox("adasd", Model.travel_request.request_type.Value == true ? "Planned" : "Unplanned", new { @style = "border:0px;", @readonly = "readonly" })
                    <h5 class="h5a">Going Overseas :</h5>
                    @Html.TextBox("adasd", Model.travel_request.overseas_flag.Value == true ? "Yes" : "No", new { @readonly = "readonly", @style = "border:0px;" })
                    <h5 class="h5a">New or Renewal Passport :</h5>
                    @Html.TextBox("adasd", Model.travel_request.passport_flag == true ? "Yes" : "No", new { @style = "border:0px;", placeholder = "Reason Assigment", @readonly = "readonly" })
                    <h5 class="h5a">Destination :</h5>
                    <label>@Html.DisplayFor(m => m.travel_request.destination_1, new { @readonly = "readonly" })</label>
                    @if (Model.travel_request.destination_2 != null)
                    {
                        <label>-</label>
                        <label>@Html.DisplayFor(m => m.travel_request.destination_2, new { @readonly = "readonly" })</label>
                    }
                    @if (Model.travel_request.destination_3 != null)
                    {
                        <label>-</label>
                        <label>@Html.DisplayFor(m => m.travel_request.destination_3, new { @readonly = "readonly" })</label>
                    }
                    <h5 class="h5a">Departure Date :</h5>
                    <p>@Html.DisplayFor(m => m.travel_request.startDate_1, new { @type = "datetime-local", placeholder = "Departure", @readonly = "readonly" })</p>
                    @*@if (Model.travel_request.endDate_1 != null)
                        {
                            <h5 class="h5a">Return Date :</h5>
                            <p>@Html.DisplayFor(m => m.travel_request.endDate_1, new { @type = "datetime-local", placeholder = "Return", @readonly = "readonly" })</p>
                        }*@
                    @if (Model.travel_request.endDate_3 != null)
                    {
                        <h5 class="h5a">Return Date :</h5>
                        <p>@Html.DisplayFor(m => m.travel_request.endDate_3, new { @type = "datetime-local", placeholder = "Return", @readonly = "readonly" })</p>
                    }
                    else if (Model.travel_request.endDate_2 != null)
                    {
                        <h5 class="h5a">Return Date :</h5>
                        <p>@Html.DisplayFor(m => m.travel_request.endDate_2, new { @type = "datetime-local", placeholder = "Return", @readonly = "readonly" })</p>
                    }
                    else
                    {
                        <h5 class="h5a">Return Date :</h5>
                        <p>@Html.DisplayFor(m => m.travel_request.endDate_1, new { @type = "datetime-local", placeholder = "Return", @readonly = "readonly" })</p>
                    }
                
                    <div class="wellIn2">
                        <span><strong>CURRENT STATUS :</strong></span>
                    </div>
                    <div style="margin-bottom:0px; padding-bottom:0px;" class="clearfix main">
                        @for (int k = 0; k < ViewBag.Approvalnum; k++)
                        {
                            if (ViewBag.Bossname[k] == null) { break; }

                            <div class="main1">
                                @if ((k == ViewBag.Approvalnum - 1))
                                {
                                    <div class="buled">
                                        <div class="bulet1" style="background: rgb(246, 246, 246);">
                                            <div class="buled2" style="background: rgb(128, 128, 128);">
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="bulet">
                                        <div class="bulet1" style="background: rgb(246, 246, 246);">
                                            <div class="buled2" style="background: rgb(128, 128, 128);">
                                            </div>
                                        </div>
                                    </div>
                                }
                                <div class="teks" style="max-width:250px;min-width:250px;">
                                    <div style="color:gray" class="teks1">
                                        @if (k >= ViewBag.StatusState.Count)
                                        {
                                            <span>@Html.Label("Waiting For ", new { @style = "color:orange; margin-right:5px;" })</span>
                                            <span>@ViewBag.Bossname[k]</span>
                                        }
                                        else
                                        {
                                            if (ViewBag.StatusState[k] == "1")
                                            {
                                                <span>@Html.Label("Approved By ", new { @style = "color:blue; margin-right:5px;" })</span>
                                                <span>@ViewBag.Bossname[k]</span>
                                            }
                                            else
                                            if (ViewBag.StatusState[k] == "2" || ViewBag.StatusState[k] == "3")
                                            {
                                                <span>@Html.Label("Rejected By ", new { @style = "color:red; margin-right:5px;" })</span>
                                                <span>@ViewBag.Bossname[k]</span>
                                                k = ViewBag.Approvalnum - 1;
                                            }
                                            else
                                            {
                                                <span>@Html.Label("Waiting For ", new { @style = "color:orange; margin-right:5px;" })</span>
                                                <span>@ViewBag.Bossname[k]</span>
                                            }
                                        }
                                    </div>
                                </div>

                                <div class="lab">
                                    <div class="lab1">
                                        @*@Html.DisplayFor(m => m.travel_request.apprv_by_lvl1, new { @readonly = "readonly" })*@
                                    </div>
                                </div>
                            </div>


                            <div class="main1"></div>

                        }
                    </div>
                    <div class="wellIn2">
                        <span><strong>LIST PARTICIPANTS :</strong></span>
                    </div>
                    <div style="text-align:left;width:444px;height:200px; overflow-y:scroll; border:0px;">
                        <ol style="margin-top:20px;margin-left:-20px;">
                            @for (int i = 0; i < Model.participants.Count; i++)
                            {
                                <li>
                                    @Html.TextBox("aaaa", ModelList[i], new { @readonly = "readonly", @style = "border:0px;color:grey;" })
                                </li>
                                @Html.HiddenFor(m => m.participants[i].no_reg)
                                @Html.HiddenFor(m => m.participants[i].no_reg_parent)
                            }
                        </ol>
                    </div>
                    <br />
                    <button type="button" class="btn btn-default btn-xs" onclick="goBack()">Back</button>
                    <button style="position:relative;left:10px" type="submit" name="download" value="download" class="btn btn-info btn-xs">Download</button>
                    @if (Model.travel_request.status_request == null)
                    {
                        <button type="button" style="width:145px; position:relative;left:10px" class="btn btn-danger btn-lg" data-toggle="modal" data-target=".bs-example-modal-sm" value="Submit">Drop Request</button>
                        <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div style="height:50px" class="modal-header">
                                        <h4 class="modal-title" id="mySmallModalLabel">Notification</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div style="text-align:center;">
                                            <strong>Are you sure you want to drop this request ?? </strong>
                                            <br />click Yes to drop
                                        </div>
                                        <div style="margin:10px 50px;text-align:center;">
                                            <span> <button type="submit" style="position:center;" class="btn btn-danger btn-xs" name="drop" value="submit">Yes</button></span>
                                            <span> <button type="button" style="position:center;" class="btn btn-info btn-xs" name="close" data-dismiss="modal">No</button></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <br />
                </div>
            </form>
        </div>
        <hr />
    </div>
}

CONTRAST_WEB/CONTRAST_WEB/Views/TravelStatus/SubmittedMSTR.cshtml
@{
    ViewBag.Title = "TRAVEL BTA REVISION";
    Layout = "~/Views/Shared/_LayoutLg.cshtml";
}

<div class="container">
    <div style="margin-top:100px" class="row">
        <div class="col-md-11 col-md-offset-1">
            <h4 style="text-align:left; padding:10px; margin-bottom:0px;"></h4>
        </div>
        <div class="col-md-11 col-md-offset-1">
            <h3 style="text-align:left; margin-top:100px; padding:0 10px;">Your request has been canceled, please press back button on the left top of your screen</h3>
        </div>


    </div>
    <hr />
    <div class="col-md-11 col-md-offset-1">
        <h4 style="text-align:left; margin-top:0px; padding:0 10px;">Thank You </h4>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link href="~/Scripts/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui.js"></script>